# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8e4d101fdc4670a3afaae485c94090552370fe501b17adda78062b38421291e7c6e13e3ea1b282675fb2570ad36a9ab24fcc4dab7650651759296eef90db6dc

test:
  secret_key_base: eabf5f2743c35006bffee6039d70c223f0daeac5ac1ecf86f705e979d968933f26a3c688ae76efb9c188a7752d1699bb59b412dc9fad57c6f9a76ddf6f3955f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
